version: '3'
services:
  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: 'secret cookie'
    ports:
      - 15672:15672
      - 15671:15671
      - 5672:5672
  api:
    build:
      context: .
      dockerfile: ./API/Dockerfile
    ports:
      - 8000:5000
      #- 8443:443
    depends_on: 
      - rabbitmq3
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - RabbitMQPort=5672
      - RabbitMQHost=rabbitmq
  back:
    build:
      context: .
      dockerfile: ./BackService/Dockerfile
    ports:
      - 9000:6000
      #- 9443:443
    depends_on: 
      - rabbitmq3
    environment:
      - ASPNETCORE_URLS=http://+:6000
      - RabbitMQPort=5672
      - RabbitMQHost=rabbitmq